# AI-Native Code Agent Configuration

[model]
# Model provider: "openai", "anthropic", or "local"
provider = "zhipu"
model_name = "GLM-4.6"
# Use environment variable for API key: ${ZHIPU_API_KEY}
api_key = "${ZHIPU_API_KEY}"
# Optional: custom endpoint for zhipu
endpoint = "https://open.bigmodel.cn/api/paas/v4/"
max_tokens = 4000
temperature = 0.7

[execution]
max_steps = 50
timeout_seconds = 300
max_retries = 3
retry_delay_seconds = 2

[safety]
enable_safety_checks = true
allowed_directories = [".", "/tmp"]
blocked_commands = ["rm -rf /", "format", "fdisk", "dd if=", "shutdown", "reboot"]
max_file_size_bytes = 10485760  # 10MB

[tools]
auto_discovery = true
# custom_tools_path = "./custom_tools"
enabled_tools = ["read_file", "write_file", "run_command", "list_files"]
disabled_tools = []

[logging]
level = "info"
file = "agent.log"
console = true
format = "pretty"  # "pretty", "json", "compact"