# AI-Native Code Agent Configuration

[model]
# Model provider: "zhipu", "deepseek", "moonshot", "openai", "anthropic", "aliyun", "longcat", "volcengine"
provider = "deepseek"
model_name = "deepseek-chat"
# Use environment variable for API key or set directly
api_key = "sk-78f437f4e0174650ae18734e6ec5bd03"
# Optional: custom endpoint (will use default if not specified)
endpoint = "https://api.deepseek.com/v1"
max_tokens = 4000
temperature = 0.7

[execution]
max_steps = 50
timeout_seconds = 300
max_retries = 3
retry_delay_seconds = 2

[safety]
enable_safety_checks = true
allowed_directories = [".", "/tmp"]
blocked_commands = ["rm -rf /", "format", "fdisk", "dd if=", "shutdown", "reboot"]
max_file_size_bytes = 10485760  # 10MB

[tools]
auto_discovery = true
# custom_tools_path = "./custom_tools"
enabled_tools = ["read_file", "write_file", "run_command", "list_files"]
disabled_tools = []

[logging]
level = "info"
file = "agent.log"
console = true
format = "pretty"  # "pretty", "json", "compact"